In [3]:
import numpy as np

# Sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# four movies
node_visible = 4

# three genres
node_hidden = 3

# decide how much to update weight/bias each step
learning_rate = 0.1

# Initialize weights/bias
# weight = interaction
#[W_11,W_21,W_31,W_41] ->genre 1
#[W_12,W_22,W_32,W_42] ->genre 2
#[W_13,W_23,W_33,W_43] ->genre 3
# mov1,mov2,mov3,mov4

W = np.full((node_hidden,node_visible),0.1)

# bias = score for each individual node
visible_bias = np.zeros(node_visible)
hidden_bias = np.zeros(node_hidden)

# Training data
train_set = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1],[1, 1, 0, 0], [0, 1, 0, 1], [0, 1, 1, 1], [0, 0, 0, 1]])

iteration = 10000

for i in range(iteration):
    for scenario in train_set:

        # contrastive divergence
        # increase existing pattern's probability
            # use gibb's sampling
            # choose a possible scenario matching current scenario:
        hidden_prob = np.sum(W*scenario,axis = 1)
        chosen_hidden = [np.random.binomial(1, sigmoid(hidden_bias[0]+hidden_prob[0])),np.random.binomial(1, sigmoid(hidden_bias[1]+hidden_prob[1])),np.random.binomial(1, sigmoid(hidden_bias[2]+hidden_prob[2]))]
        
        # decrease a random pattern's probability
        # random decrease 还没做完捏
        #neg_scenario = [np.random.binomial(1,.5),np.random.binomial(1,.5),np.random.binomial(1,.5),np.random.binomial(1,.5)]
        #neg_hidden = [np.random.binomial(1,.5),np.random.binomial(1,.5),np.random.binomial(1,.5)]

        # update bias/weight according to scenario chosen
        for i in range(len(scenario)):
            if scenario[i] == 1:
                visible_bias[i] += learning_rate
            #if neg_scenario[i] == 1:
                #visible_bias[i] -= learning_rate
            for j in range(len(chosen_hidden)):
                if scenario[i] == 1 and chosen_hidden[j] == 1:
                    W[j,i] += learning_rate
                #if neg_scenario[i] == 1 and neg_hidden[j] == 1:
                    #W[j,i] -= learning_rate

        for j in range(len(chosen_hidden)):
            if chosen_hidden[j] == 1:
                hidden_bias[j] += learning_rate
            #if neg_hidden[j] == 1:
                #hidden_bias[j] -= learning_rate

        

print (W)
print(hidden_bias)
print(visible_bias)


[[1999.9 3999.9 2000.  4000. ]
 [1999.9 3999.7 2000.  3999.7]
 [2000.  3999.8 1999.8 3999.5]]
[7999.70000001 7999.20000001 7999.00000001]
[2000. 4000. 2000. 4000.]
